---
abstract: 'Cairo/Pango backend for Graphics::Primitive'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  File::Spec: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Graphics-Primitive-Driver-CairoPango
no_index:
  directory:
    - inc
    - t
requires:
  Cairo: 1.060
  Geometry::Primitive: 0.12
  Graphics::Primitive: 0.32
  Gtk2: 1.183
  IO::File: 0
  Math::Complex: 1.54
  Moose: 0.57
version: 0.2
